language: python
python:
 - "2.7"
 - "3.4"
env:
 - DJANGO="django==1.7"
 - DJANGO="django==1.8"
 - DJANGO="django==1.9"
 - DJANGO="django==1.10"
 - DJANGO="django==1.11"
install:
 - pip install $DJANGO
script:
 - python setup.py test
